-- Create OTP table for storing OTP codes
CREATE TABLE IF NOT EXISTS otp (
  id INT AUTO_INCREMENT PRIMARY KEY,
  phone VARCHAR(255) NOT NULL,
  otp VARCHAR(10) NOT NULL,
  expiresAt DATETIME NOT NULL,
  verified TINYINT(1) NOT NULL DEFAULT 0,
  attempts INT NOT NULL DEFAULT 0,
  type ENUM('USER_LOGIN', 'CUSTOMER_LOGIN', 'REGISTRATION') NOT NULL DEFAULT 'USER_LOGIN',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_phone_verified_expires (phone, verified, expiresAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
